const elem1 = document.querySelector(".elem1");
const elem2 = document.querySelector(".elem2");
const elem3 = document.querySelector(".elem3");
const elem4 = document.querySelector(".elem4");
const elem5 = document.querySelector(".elem5");
const elem6 = document.querySelector(".elem6");
const elem7 = document.querySelector(".elem7");
const elem8 = document.querySelector(".elem8");
const elem9 = document.querySelector(".elem9");
const elem10 = document.querySelector(".elem10");
const elem11 = document.querySelector(".elem11");
const elem12 = document.querySelector(".elem12");
const elem13 = document.querySelector(".elem13");
const elem14 = document.querySelector(".elem14");
const elem15 = document.querySelector(".elem15");
const elem16 = document.querySelector(".elem16");
const msg1 = document.querySelector(".msg1");
const msg2 = document.querySelector(".msg2");
const msg3 = document.querySelector(".msg3");
const msg4 = document.querySelector(".msg4");
const msg5 = document.querySelector(".msg5");
const msg6 = document.querySelector(".msg6");
const msg7 = document.querySelector(".msg7");
const msg8 = document.querySelector(".msg8");
const msg9 = document.querySelector(".msg9");
const msg10 = document.querySelector(".msg10");
const msg11 = document.querySelector(".msg11");
const msg12 = document.querySelector(".msg12");
const msg13 = document.querySelector(".msg13");
const msg14 = document.querySelector(".msg14");
const msg15 = document.querySelector(".msg15");
const msg16 = document.querySelector(".msg16");

elem1.addEventListener("click", (e) => {
  e.preventDefault();
  msg1.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem2.addEventListener("click", (e) => {
  e.preventDefault();
  msg2.style.display = "block";
  msg1.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem3.addEventListener("click", (e) => {
  e.preventDefault();
  msg3.style.display = "block";
  msg2.style.display = "none";
  msg1.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem4.addEventListener("click", (e) => {
  e.preventDefault();
  msg4.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg1.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem5.addEventListener("click", (e) => {
  e.preventDefault();
  msg5.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg1.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem6.addEventListener("click", (e) => {
  e.preventDefault();
  msg6.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg1.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});

elem7.addEventListener("click", (e) => {
  e.preventDefault();
  msg7.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg1.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem8.addEventListener("click", (e) => {
  e.preventDefault();
  msg8.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg1.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem9.addEventListener("click", (e) => {
  e.preventDefault();
  msg9.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg1.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem10.addEventListener("click", (e) => {
  e.preventDefault();
  msg10.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg1.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem11.addEventListener("click", (e) => {
  e.preventDefault();
  msg11.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg1.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem12.addEventListener("click", (e) => {
  e.preventDefault();
  msg12.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg1.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem13.addEventListener("click", (e) => {
  e.preventDefault();
  msg13.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg1.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem14.addEventListener("click", (e) => {
  e.preventDefault();
  msg14.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg1.style.display = "none";
  msg15.style.display = "none";
  msg16.style.display = "none";
});
elem15.addEventListener("click", (e) => {
  e.preventDefault();
  msg15.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg1.style.display = "none";
  msg16.style.display = "none";
});
elem16.addEventListener("click", (e) => {
  e.preventDefault();
  msg16.style.display = "block";
  msg2.style.display = "none";
  msg3.style.display = "none";
  msg4.style.display = "none";
  msg5.style.display = "none";
  msg6.style.display = "none";
  msg7.style.display = "none";
  msg8.style.display = "none";
  msg9.style.display = "none";
  msg10.style.display = "none";
  msg11.style.display = "none";
  msg12.style.display = "none";
  msg13.style.display = "none";
  msg14.style.display = "none";
  msg15.style.display = "none";
  msg1.style.display = "none";
});
